name: Build and push docker images
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push the Docker image for the Next.js app
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./next_app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/next-app:latest
      - name: Build and push the Docker image for Video processor
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./video_processor/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/video-processor:latest
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/next-app:latest
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/video-processor:latest
            sudo docker-compose -f ./app/docker-compose.yml down
            sudo docker stop $(sudo docker ps -q)
            sudo docker rm $(sudo docker ps -aq)
            sudo docker-compose -f ./app/docker-compose.yml up -d --force-recreate --no-deps
            sudo docker image prune -a -f
